### ISSUE TITLE
Cannot start Project & `Cannot start nuxt:  formatter is not a function`

### ISSUE THREAD

**Issue by yeonjulee1005** [nuxt-modules/stylelint#113]
I try below 2 cases:

1. local project

```
------------------------------
- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.9.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  bun@1.0.21
- Builder:          -
- User Config:      app, modules, css, ui, components, imports, pinia, supabase, vite, runtimeConfig, content, htmlValidator, fontMetrics, pwa, i18n, dayjs, devtools, experimental, stylelint, vueuse, typescript, robots, site
- Runtime Modules:  @nuxt/ui@2.12.0, @nuxt/image@1.2.0, @nuxt/devtools@1.0.6, @nuxt/content@2.10.0, @nuxtjs/device@3.1.1, @nuxtjs/fontaine@0.4.1, @nuxtjs/robots@3.0.0, @nuxtjs/supabase@1.1.4, @nuxtjs/eslint-module@4.1.0, @nuxtjs/html-validator@1.6.0, @nuxtjs/stylelint-module@5.0.1, @nuxtjs/i18n@8.0.0, nuxt-time@0.1.1, nuxt-icon@0.6.8, nuxt-simple-sitemap@4.2.0, @vite-pwa/nuxt@0.3.6, @vueuse/nuxt@10.7.2, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, dayjs-nuxt@2.1.9
- Build Modules:    -
------------------------------
```

- setting  in `nuxt.config.ts`
```
modules: [
  '@nuxtjs/stylelint-module'
],
stylelint: {
  lintOnStart: true,
}
```

- run dev project
- occur error

```
Cannot start nuxt:  formatter is not a function

  at node_modules/vite-plugin-stylelint/dist/shared/vite-plugin-stylelint.8a1a2f6f.mjs:184:18
  at async node_modules/vite-plugin-stylelint/dist/shared/vite-plugin-stylelint.8a1a2f6f.mjs:161:29
  at async Context.buildStart (node_modules/vite-plugin-stylelint/dist/index.mjs:49:9)
  at async Promise.all (index 9)
  at async hookParallel (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:63609:9)
  at async Object.buildStart (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:63961:13)
  at async node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:60660:13
  at async _createServer (node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:60691:9)
  at async buildClient (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.NwMCGWpb.mjs:529:24)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.NwMCGWpb.mjs:1462:3)
  ```
<img width="543" alt="image" src="https://github.com/nuxt-modules/stylelint/assets/57179957/e8deb903-bd22-4443-8761-59edf2762d38">

---

2. stackblitz

[Reproduction](https://stackblitz.com/edit/github-mrvmgv?file=package.json,nuxt.config.ts)

- fork > nuxt 3.9.1
- package manager use `npm`
- install `stylelint`, `@nuxtjs/stylelint-module` 
- setting  in `nuxt.config.ts`
```
modules: [
  '@nuxtjs/stylelint-module'
],
stylelint: {
  lintOnStart: true,
}
```
- run project

- occure error

```
[오전 9:52:08]  ERROR  Error while requiring module @nuxtjs/eslint-module: Error: Cannot find module '/home/projects/github-mrvmgv/@nuxtjs/eslint-module'
Require stack:
- /home/projects/github-mrvmgv/index.js


 ERROR  Cannot start nuxt:  Cannot find module '/home/projects/github-mrvmgv/@nuxtjs/eslint-module'  오전 9:52:08
Require stack:
- /home/projects/github-mrvmgv/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (https://githubmrvmgv-wex2.w-credentialless.staticblitz.com/blitz.babcaeac.js:54:12642)
  at Function.resolve (https://githubmrvmgv-wex2.w-credentialless.staticblitz.com/blitz.babcaeac.js:98:2256)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:251223)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:2294:36)
  at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2299:24)
  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2535:92)
  at async Module.installModule (node_modules/@nuxt/kit/dist/index.mjs:2491:47)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3844:7)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:268:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:200:7)

```

Where should I check?

**Comment by yeonjulee1005** [comment]
I checked problem in `.scss` file parsing. 

`// ` <- annotation parsing is problem.. 
this issue closed! and i'll create another issue in `nuxt/nuxt`

**Comment by mojabyte** [comment]
I'm facing the same problem. Have you found any workarounds?
